################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../app.c \
../app_lcd.c \
../bmp.c \
../dmd_memlcd.c \
../glib.c \
../glib_bitmap.c \
../glib_circle.c \
../glib_font_narrow_6x8.c \
../glib_font_normal_8x8.c \
../glib_font_number_16x20.c \
../glib_line.c \
../glib_polygon.c \
../glib_rectangle.c \
../glib_string.c \
../lcd.c \
../lcd_display.c \
../lcd_spi.c \
../main.c 

OBJS += \
./app.o \
./app_lcd.o \
./bmp.o \
./dmd_memlcd.o \
./glib.o \
./glib_bitmap.o \
./glib_circle.o \
./glib_font_narrow_6x8.o \
./glib_font_normal_8x8.o \
./glib_font_number_16x20.o \
./glib_line.o \
./glib_polygon.o \
./glib_rectangle.o \
./glib_string.o \
./lcd.o \
./lcd_display.o \
./lcd_spi.o \
./main.o 

C_DEPS += \
./app.d \
./app_lcd.d \
./bmp.d \
./dmd_memlcd.d \
./glib.d \
./glib_bitmap.d \
./glib_circle.d \
./glib_font_narrow_6x8.d \
./glib_font_normal_8x8.d \
./glib_font_number_16x20.d \
./glib_line.d \
./glib_polygon.d \
./glib_rectangle.d \
./glib_string.d \
./lcd.d \
./lcd_display.d \
./lcd_spi.d \
./main.d 


# Each subdirectory must supply rules for building sources it contributes
app.o: ../app.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"app.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

app_lcd.o: ../app_lcd.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"app_lcd.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

bmp.o: ../bmp.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"bmp.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

dmd_memlcd.o: ../dmd_memlcd.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"dmd_memlcd.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib.o: ../glib.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"glib.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib_bitmap.o: ../glib_bitmap.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"glib_bitmap.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib_circle.o: ../glib_circle.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"glib_circle.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib_font_narrow_6x8.o: ../glib_font_narrow_6x8.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"glib_font_narrow_6x8.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib_font_normal_8x8.o: ../glib_font_normal_8x8.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"glib_font_normal_8x8.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib_font_number_16x20.o: ../glib_font_number_16x20.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"glib_font_number_16x20.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib_line.o: ../glib_line.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"glib_line.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib_polygon.o: ../glib_polygon.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"glib_polygon.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib_rectangle.o: ../glib_rectangle.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"glib_rectangle.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

glib_string.o: ../glib_string.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"glib_string.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lcd.o: ../lcd.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"lcd.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lcd_display.o: ../lcd_display.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"lcd_display.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

lcd_spi.o: ../lcd_spi.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"lcd_spi.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

main.o: ../main.c subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m33 -mthumb -std=c18 '-DDEBUG=1' '-DDEBUG_EFM=1' '-DEFR32MG21A020F1024IM32=1' '-DSL_BOARD_NAME="BRD4180B"' '-DSL_BOARD_REV="A03"' '-DHARDWARE_BOARD_DEFAULT_RF_BAND_2400=1' '-DHARDWARE_BOARD_SUPPORTS_1_RF_BAND=1' '-DHARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1' '-DHFXO_FREQ=38400000' '-DSL_COMPONENT_CATALOG_PRESENT=1' '-DCMSIS_NVIC_VIRTUAL=1' '-DCMSIS_NVIC_VIRTUAL_HEADER_FILE="cmsis_nvic_virtual.h"' '-DSL_CODE_COMPONENT_CORE=core' '-DSL_CODE_COMPONENT_SLEEPTIMER=sleeptimer' -I"D:\IOT\Thuc hanh\SiliconLab\bai3\config" -I"D:\IOT\Thuc hanh\SiliconLab\bai3\autogen" -I"D:\IOT\Thuc hanh\SiliconLab\bai3" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/Device/SiliconLabs/EFR32MG21/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/board/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/clock_manager/src" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/CMSIS/Core/Include" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//hardware/driver/configuration_over_swo/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/driver/debug/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/device_init/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/emlib/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/interrupt_manager/inc/arm" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/memory_manager/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/common/toolchain/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/system/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/sleeptimer/inc" -I"D:/SiliconLab/simplicity_sdk_suite_v2024_6_2-001/simplicity_sdk_5//platform/service/udelay/inc" -Os -Wall -Wextra -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -imacrossl_gcc_preinclude.h -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mcmse --specs=nano.specs -c -fmessage-length=0 -MMD -MP -MF"main.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


